### ISSUE TITLE
can't import component

### ISSUE THREAD

**Issue by mandihof** [metayoub/qodly_webCam#1]
hi, 
i wanted to import this component to Qodly but it doesn't work.

"The upload of the custom component failed.
Make sure you are importing a"

greetings
Manfred

**Comment by metayoub** [comment]
Hello @mandihof,

Can you give me more details, which release did you try to use.
DO you use qodly.com or 4D. which version do you use ?

Ayoub

**Comment by mandihof** [comment]
Hi Ayoub,

i use 4dv20R6.  i downloaded this release
https://github.com/metayoub/qodly_webCam/releases/tag/0.1.0

i tried to import the qodly_b6e080fa86a3580e4021.zip file

**Comment by metayoub** [comment]
can you try this one ?
https://github.com/metayoub/qodly_webCam/releases/tag/0.3.1

**Comment by mandihof** [comment]
i had a talk to christian on the 4d tour in vienna yesterday. he told me that i have to create the "shareg"customcomponents" folder on my own. 

i also installed the final v20r6 and now it works,

thank you
